<div class="section animated-section">
	<h2 class="title text-blue"><span>Achievement</span></h2>
	<div class="section-content">
		<ul class="achievement">
			<li class="animated-item">
				<i class="text-blue fa fa-check"></i> BuzzHeat on TV: (<a href="https://vtv.vn/video/ca-phe-khoi-nghiep-05-3-2018-284995.htm" target="_blank">VTV1</a>)
			</li>
			<li class="animated-item">
				<i class="text-blue fa fa-check"></i> Outstanding student of Ho Chi Minh City 2014: (<a href="http://tuoitre.vn/tin/nhip-song-tre/20150109/thu-linh-5-tot/696387.html" target="_blank">Tuoi Tre News</a>)
			</li>
			<li class="animated-item">
				<i class="text-blue fa fa-check"></i> The member of JENESYS Programme 2.0 in Japan
			</li>
			<li class="animated-item">
				<i class="text-blue fa fa-check"></i> The third prize of Student Scientific Research - Eureka 2013
			</li>
			<li class="animated-item">
				<i class="text-blue fa fa-check"></i> The second prize of UIT Student Scientific Research 2013
			</li>
			<li class="animated-item">
				<i class="text-blue fa fa-check"></i> President of national union of students at University of Information Technology
			</li>
		</ul>
	</div>
</div>