<div class="section blog animated-section">
	<h2 class="title text-blue"><span>Personal Blog</span></h2>
	<div class="section-content">
		<p class="text-justify">I also love writing blog posts in my free time. Here is my publication <a href="https://medium.com/tinyso">https://medium.com/tinyso</a> and I'm getting many positive results from this.</p>
		<ul class="achievement">
			<li><i class="text-blue fa fa-check"></i> Page #1 Google for "react create modal": <a href="https://medium.com/tinyso/how-to-create-a-modal-component-in-react-from-basic-to-advanced-a3357a2a716a">How to create a Modal Component in React</a> </li>
			<li><i class="text-blue fa fa-check"></i> Page #1 Google for "react auto logout": <a href="https://medium.com/tinyso/how-to-detect-inactive-user-to-auto-logout-by-using-idle-timeout-in-javascript-react-angular-and-b6279663acf2">How to detect inactive user to auto logout in React</a> </li>
			<li><i class="text-blue fa fa-check"></i> Page #1 Google for "react create carousel": <a href="https://medium.com/tinyso/how-to-create-the-responsive-and-swipeable-carousel-slider-component-in-react-99f433364aa0">How to create the responsive and swipeable Carousel — Slider component in React</a> </li>
		</ul>
	</div>
</div>