<header>
	<div class="row row-3-9">
		<div class="text-center">
			<img class="profile-picture" src="images/profile.jpg" />
		</div>
		<div>
			<h1 class="title text-blue">Thi Tran</h1>
			<h2 class="subtitle text-blue">Software Engineer</h2>
			<div class="personal-info row row-5-7">
				<div>
					<p>
						<span class="text-blue"><i class="fa fa-envelope"></i></span> dinhthibc@gmail.com
					</p>
					<p>
						<span class="text-blue"><i class="fa fa-mobile-phone"></i></span> (+84) 378850061
					</p>
					<p>
						<span class="text-blue"><i class="fa fa-chrome"></i></span> about.trandinhthi.com
					</p>
					<p>
						<span class="text-blue"><i class="fa fa-birthday-cake"></i></span> 1992-02-25
					</p>
					<p>
						<span class="text-blue"><i class="fa fa-map-marker"></i></span> Ho Chi Minh city
					</p>
					<p>
						<span class="text-blue"><i class="fa fa-map-marker"></i></span> Singapore (Dependant Pass)
					</p>
				</div>
				<div>
					<p>
						<span class="text-blue"><i class="fa fa-book"></i></span> Bachelor's Degree in Software Engineering
					</p>
					<p>
						<span class="text-blue"><i class="fa fa-briefcase"></i></span> Senior Software Engineer at <a target="_blank" href="https://weroster.com.au">WeRoster</a> (since 11/2017)
					</p>
					<p>
						<i class="fa fa-briefcase"></i> Former Senior Software Engineer at <a target="_blank" href="https://buzzheat.com">BuzzHeat</a> (~2.5 years)
					</p>
					<p>
						<i class="fa fa-briefcase"></i> Former Backend Developer at <a target="_blank" href="https://www.siliconstraits.vn/">Silicon Straits</a> (1 year)
					</p>
					<p>
						<i class="fa fa-briefcase"></i> Former Software Engineer at <a target="_blank" href="https://buzzmetrics.com">BuzzMetrics</a> (~2.5 years)
					</p>
				</div>
			</div>
		</div>
	</div>
</header>
