<header class="animated-section">
	<div class="row row-3-9">
		<div class="text-center">
			<img class="profile-picture animated-item" src="images/profile-2021.jpg" />
		</div>
		<div>
			<h1 class="title text-blue animated-item">Thi Tran</h1>
			<h2 class="subtitle text-blue animated-item">Software Engineer</h2>
			<div class="personal-info row row-5-7">
				<div>
					<p class="animated-item">
						<span class="text-blue"><i class="fa fa-envelope"></i></span> dinhthibc@gmail.com
					</p>
					<p class="animated-item">
						<span class="text-blue"><i class="fa fa-mobile-phone"></i></span> (+65) 8416 8927
					</p>
					<p class="animated-item">
						<span class="text-blue"><i class="fa fa-chrome"></i></span> about.trandinhthi.com
					</p>
					<p class="animated-item">
						<span class="text-blue"><i class="fa fa-map-marker"></i></span> Singapore
					</p>
				</div>
				<div>
					<p class="animated-item">
						<span class="text-blue"><i class="fa fa-book"></i></span> Bachelor's Degree in Software Engineering
					</p>
					<p class="animated-item">
						<span class="text-blue"><i class="fa fa-briefcase"></i></span> Full Stack Developer at PALO IT Singapore (since 07/2019)
					</p>
					<p class="animated-item">
						<i class="fa fa-briefcase"></i> Former Senior Software Engineer at <a target="_blank" href="https://weroster.com.au">WeRoster</a> (~2 years)
					</p>
					<p class="animated-item">
						<i class="fa fa-briefcase"></i> Former Senior Software Engineer at <a target="_blank" href="https://buzzheat.com">BuzzHeat</a> (~2.5 years)
					</p>
					<p class="animated-item">
						<i class="fa fa-briefcase"></i> Former Software Engineer at <a target="_blank" href="https://www.siliconstraits.vn/">Silicon Straits</a> (1 year)
					</p>
					<p class="animated-item">
						<i class="fa fa-briefcase"></i> Former Software Engineer at <a target="_blank" href="https://buzzmetrics.com">BuzzMetrics</a> (~2.5 years)
					</p>
				</div>
			</div>
		</div>
	</div>
</header>
