<div class="section animated-section">
	<h2 class="title text-blue"><span>About me</span></h2>
	<div class="section-content">
		<p class="text-justify animated-item">
			I have graduated in Software Engineering from University of Information Technology (Vietnam National University) and have <?php echo (date('Y') - 2013); ?> years in software development. I was working on many different types of projects including social listening, ride-hailing like Grab/Uber, video streaming platform, rostering, crypto, banking,... I am familiar with both backend - frontend and always keen to learn new technologies.
		</p>
	</div>
</div>