<div class="section">
	<h2 class="title text-blue"><span>About me</span></h2>
	<div class="section-content">
		<p class="text-justify">
			I have graduated Software Engineering at University of Information Technology (Vietnam National University) and have <?php echo (date('Y') - 2013); ?> years in building web application. Being a software engineer, I always keep the mindset "building products, services by heart" for every single project, every company I join.
		</p>
	</div>
</div>