<?php
$backendSkills = [
	['name' => 'PHP', 'level' => 9],
	['name' => 'Golang', 'level' => 7],
	['name' => 'NodeJS', 'level' => 6],
	['name' => 'Ubuntu/CenOS', 'level' => 6],
	['name' => 'MySQL/Postgres/Redis/MongoDB', 'level' => 8],
];

$frontendSkills = [
	['name' => 'HTML5/CSS3', 'level' => 9],
	['name' => 'JavaScript (ES6)', 'level' => 8],
	['name' => 'jQuery', 'level' => 9],
	['name' => 'Bootstrap', 'level' => 9],
	['name' => 'ReactJS', 'level' => 5],
];

?>

<div class="section">
	<h2 class="title text-blue"><span>Skills</span></h2>
	<div class="section-content row row-6-6 gap-50">
		<div>
			<ul class="skills">
				<?php foreach ($backendSkills as $skill) { ?>
					<li class="level-<?php echo $skill['level'] ?>">
						<span class="name"><?php echo $skill['name'] ?></span>
						<span class="dots">
							<?php for ($i = 0; $i < 10; $i++) { ?>
								<i class="dot"></i>
							<?php } ?>
						</span>
					</li>
				<?php } ?>
			</ul>

			<p class="text-small normal margin-top">
				<em>I love designing overall architect, scalable system, problem solving, optimise performance & deployment process.</em>
			</p>
		</div>
		<div>
			<ul class="skills">
				<?php foreach ($frontendSkills as $skill) { ?>
					<li class="level-<?php echo $skill['level'] ?>">
						<span class="name"><?php echo $skill['name'] ?></span>
						<span class="dots">
							<?php for ($i = 0; $i < 10; $i++) { ?>
								<i class="dot"></i>
							<?php } ?>
						</span>
					</li>
				<?php } ?>
			</ul>

			<p class="text-small normal margin-top">
				<em>I love playing with DOM rendering, creating animation with CSS3 and making wireframe designs come true</em>
			</p>
		</div>
	</div>
</div>