<?php
$backendSkills = [
	['name' => 'PHP', 'level' => 9],
	['name' => 'Golang', 'level' => 6],
	['name' => 'NodeJS', 'level' => 7],
	['name' => 'AWS/Ubuntu/CenOS', 'level' => 5],
	['name' => 'MySQL/Postgres', 'level' => 8],
];

$frontendSkills = [
	['name' => 'React', 'level' => 9],
	['name' => 'HTML5/CSS3', 'level' => 9],
	['name' => 'JavaScript (ES6)', 'level' => 8],
	['name' => 'jQuery/Bootstrap', 'level' => 9],
	['name' => 'Sass/Tailwind', 'level' => 7],
];

?>

<div class="section skills animated-section">
	<h2 class="title text-blue"><span>Skills</span></h2>
	<div class="section-content row row-6-6 gap-50">
		<div>
			<ul class="skills">
				<?php foreach ($backendSkills as $skill) { ?>
					<li class="level-<?php echo $skill['level'] ?> animated-item">
						<span class="name"><?php echo $skill['name'] ?></span>
						<span class="dots">
							<?php for ($i = 0; $i < 10; $i++) { ?>
								<i class="dot"></i>
							<?php } ?>
						</span>
					</li>
				<?php } ?>
			</ul>

			<p class="text-small normal margin-top animated-item">
				<em>I love designing overall architect, scalable system, problem solving, optimize performance & deployment process</em>
			</p>
		</div>
		<div>
			<ul class="skills">
				<?php foreach ($frontendSkills as $skill) { ?>
					<li class="level-<?php echo $skill['level'] ?> animated-item">
						<span class="name"><?php echo $skill['name'] ?></span>
						<span class="dots">
							<?php for ($i = 0; $i < 10; $i++) { ?>
								<i class="dot"></i>
							<?php } ?>
						</span>
					</li>
				<?php } ?>
			</ul>

			<p class="text-small normal margin-top animated-item">
				<em>I love playing with DOM manipulation, creating animations, motions with CSS/SVG and making designs come true</em>
			</p>
		</div>
	</div>
</div>