<!doctype html>
<html lang="en">
<head>
	<base href="/">
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
	<title>
		<?php echo $this->title; ?>
	</title>
	<link href="https://fonts.googleapis.com/css?family=Inconsolata:400,700" rel="stylesheet">
	<link rel="stylesheet" href="<?php echo $this->getTemplateUrl(); ?>/public/node_modules/font-awesome/css/font-awesome.min.css" />
	<meta property="og:url" content="https://about.trandinhthi.com/">
	<meta property="og:image" content="https://about.trandinhthi.com/images/profile.jpg">
	<meta property="og:title" content="Thi Tran Portfolio - Software Engineer">
	<meta property="og:site_name" content="Thi Tran">

	<?php
	foreach ($this->style as $style) {
		echo $style . "\n";
	}
	?>
	<link rel="stylesheet" href="<?php echo $this->getTemplateUrl(); ?>/public/dest/css/style.min.css<?php if ($this->config->get('env') == 'dev') { echo '?t=' . time(); } ?>">
</head>
<body>
<div style="">
	<?php require_once $this->content; ?>
</div>
<footer class="text-center hide-on-print">Powered by <a href="https://github.com/dinhthibc/about" target="_blank"><i class="fa fa-github"></i> Github</a> </footer>

<script src="<?php echo $this->getTemplateUrl(); ?>/public/node_modules/jquery/dist/jquery.min.js"></script>

<?php
foreach ($this->script as $script) {
	echo $script . "\n";
}
?>

<script src="<?php echo $this->getTemplateUrl(); ?>/public/dest/js/main.min.js<?php if ($this->config->get('env') == 'dev') { echo '?t=' . time(); } ?>"></script>

<?php if ($this->scriptFile) {
	require_once $this->scriptFile;
}
?>

<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-71630506-6"></script>
<script>
	window.dataLayer = window.dataLayer || [];
	function gtag(){dataLayer.push(arguments);}
	gtag('js', new Date());

	gtag('config', 'UA-71630506-6');
</script>

</body>
</html>