<?php
$backendSkills = [
	['name' => 'PHP', 'level' => 9],
	['name' => 'Golang', 'level' => 6],
	['name' => 'NodeJS', 'level' => 6],
	['name' => 'Ubuntu/CenOS', 'level' => 6],
	['name' => 'MySQL/Redis/Postgres', 'level' => 8],
];

$frontendSkills = [
	['name' => 'HTML5/CSS3', 'level' => 9],
	['name' => 'JavaScript (ES6)', 'level' => 8],
	['name' => 'jQuery', 'level' => 9],
	['name' => 'Bootstrap', 'level' => 9],
	['name' => 'ReactJS', 'level' => 5],
];

?>

<div class="wrapper">
	<header>
		<div class="row row-3-9">
			<div>
				<img class="profile-picture" src="images/profile.jpg" />
			</div>
			<div>
				<h1 class="title text-blue">Thi Tran</h1>
				<h2 class="subtitle text-blue">Software Engineer</h2>
				<div class="personal-info row row-5-7">
					<div>
						<p>
							<span class="text-blue"><i class="fa fa-envelope"></i> Email: </span>dinhthibc@gmail.com
						</p>
						<p>
							<span class="text-blue"><i class="fa fa-mobile-phone"></i> Phone: </span>(+84) 378850061
						</p>
						<p>
							<span class="text-blue"><i class="fa fa-chrome"></i> Website: </span>about.trandinhthi.com
						</p>
					</div>
					<div>
						<p>
							<span class="text-blue"><i class="fa fa-book"></i> Education: </span>Bachelor's Degree in Software Engineering
						</p>
						<p>
							<span class="text-blue"><i class="fa fa-map-marker"></i> Location: </span>Ho Chi Minh City, Vietnam
						</p>
						<p>
							<span class="text-blue"><i class="fa fa-calendar"></i> Date of birth: </span>1992-02-25
						</p>
					</div>
				</div>
			</div>
		</div>
	</header>
	<div class="section">
		<h2 class="title text-blue"><span>About me</span></h2>
		<div class="section-content">
			<p>
				I've graduated Software Engineering at University of Information Technology (Vietnam National University) for 3 years and have 6 years in building web application. Being a software engineer, I always put mindset "building products, services by heart" for every single project, every company I join.
			</p>
		</div>
	</div>
	<div class="section">
		<h2 class="title text-blue"><span>Skills</span></h2>
		<div class="section-content row row-6-6 gap-50">
			<div>
				<ul class="skills">
					<?php foreach ($backendSkills as $skill) { ?>
					<li class="level-<?php echo $skill['level'] ?>">
						<span class="name"><?php echo $skill['name'] ?></span>
						<span class="dots">
							<?php for ($i = 0; $i < 10; $i++) { ?>
							<i class="dot"></i>
							<?php } ?>
						</span>
					</li>
					<?php } ?>
				</ul>

				<p class="text-small normal margin-top">
					<em>I love designing overall architect, scalable system, problem solving, optimise performance & deployment process.</em>
				</p>
			</div>
			<div>
				<ul class="skills">
					<?php foreach ($frontendSkills as $skill) { ?>
						<li class="level-<?php echo $skill['level'] ?>">
							<span class="name"><?php echo $skill['name'] ?></span>
						<span class="dots">
							<?php for ($i = 0; $i < 10; $i++) { ?>
								<i class="dot"></i>
							<?php } ?>
						</span>
						</li>
					<?php } ?>
				</ul>

				<p class="text-small normal margin-top">
					<em>I love playing with DOM rendering, creating animation with CSS3 and making wireframe designs come true</em>
				</p>
			</div>
		</div>
	</div>
</div>